### ISSUE TITLE
Overflow when subtracing durations

### ISSUE THREAD

**Issue by Firstyear** [QnnOkabayashi/tracing-forest#11] opened 2022-03-16 00:31 UTC
```
thread 'tokio-runtime-worker' panicked at 'overflow when subtracting durations', library/core/src/time.rs:988:31
stack backtrace:
   0:        0x104e1b2a8 - std::backtrace_rs::backtrace::libunwind::trace::hbad44c2b21d61f40
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:        0x104e1b2a8 - std::backtrace_rs::backtrace::trace_unsynchronized::h664423984da6366c
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:        0x104e1b2a8 - std::sys_common::backtrace::_print_fmt::ha0bed729b1de74e6
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/sys_common/backtrace.rs:67:5
   3:        0x104e1b2a8 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h58c637f9e30d1b8a
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/sys_common/backtrace.rs:46:22
   4:        0x104e39a48 - core::fmt::write::hc16ca97d9f5e0acd
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/fmt/mod.rs:1168:17
   5:        0x104e13980 - std::io::Write::write_fmt::hd53dc7153ccce04d
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/io/mod.rs:1660:15
   6:        0x104e1db80 - std::sys_common::backtrace::_print::h52e9a34b49f28ab7
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/sys_common/backtrace.rs:49:5
   7:        0x104e1db80 - std::sys_common::backtrace::print::h0bf7306c450cdde6
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/sys_common/backtrace.rs:36:9
   8:        0x104e1db80 - std::panicking::default_hook::{{closure}}::ha41f2cf175ca93cf
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:211:50
   9:        0x104e1d728 - std::panicking::default_hook::h838498b157804a1a
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:228:9
  10:        0x104e1e144 - std::panicking::rust_panic_with_hook::h7722806c30430655
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:606:17
  11:        0x104e1deb4 - std::panicking::begin_panic_handler::{{closure}}::h265229fa7cad6de7
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:502:13
  12:        0x104e1b774 - std::sys_common::backtrace::__rust_end_short_backtrace::hfa83d61d0ed14557
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/sys_common/backtrace.rs:139:18
  13:        0x104e1dc1c - rust_begin_unwind
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:498:5
  14:        0x104e4f55c - core::panicking::panic_fmt::hd3f68d55261c2af0
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/panicking.rs:116:14
  15:        0x104e37fa0 - core::panicking::panic_display::hff68090176e91371
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/panicking.rs:72:5
  16:        0x104e37f64 - core::panicking::panic_str::h6fef52d5b430fe60
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/panicking.rs:56:5
  17:        0x104e4f4a8 - core::option::expect_failed::h25418b3d346807f3
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/option.rs:1817:5
  18:        0x104e3c490 - core::option::Option<T>::expect::hfb273a86814749af
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/option.rs:692:21
  19:        0x104e3c490 - <core::time::Duration as core::ops::arith::Sub>::sub::hc7ad54c90819303e
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/time.rs:988:9
  20:        0x104670740 - tracing_forest::tree::Span::base_duration::h3ef8a0fa1c6822c0
                               at /Users/william/development/tracing-forest/tracing-forest/src/tree/mod.rs:262:9
  21:        0x1046721a8 - tracing_forest::printer::pretty::Pretty::format_span::hcf6490919e718eef
                               at /Users/william/development/tracing-forest/tracing-forest/src/printer/pretty.rs:139:33
  22:        0x10467181c - tracing_forest::printer::pretty::Pretty::format_tree::h4a2f2d56117213c6
                               at /Users/william/development/tracing-forest/tracing-forest/src/printer/pretty.rs:84:17
  23:        0x10467268c - tracing_forest::printer::pretty::Pretty::format_span::hcf6490919e718eef
                               at /Users/william/development/tracing-forest/tracing-forest/src/printer/pretty.rs:165:13
  24:        0x10467181c - tracing_forest::printer::pretty::Pretty::format_tree::h4a2f2d56117213c6
                               at /Users/william/development/tracing-forest/tracing-forest/src/printer/pretty.rs:84:17
  25:        0x1046725c8 - tracing_forest::printer::pretty::Pretty::format_span::hcf6490919e718eef
                               at /Users/william/development/tracing-forest/tracing-forest/src/printer/pretty.rs:159:17
  26:        0x10467181c - tracing_forest::printer::pretty::Pretty::format_tree::h4a2f2d56117213c6
                               at /Users/william/development/tracing-forest/tracing-forest/src/printer/pretty.rs:84:17
  27:        0x1046715fc - <tracing_forest::printer::pretty::Pretty as tracing_forest::printer::Formatter>::fmt::he9182c9819c8a7c9
                               at /Users/william/development/tracing-forest/tracing-forest/src/printer/pretty.rs:61:9
```

**Comment by Firstyear** [comment] 2022-03-16 00:31
Very likely you need to use sub_checked here to avoid this.

**Comment by Firstyear** [comment] 2022-03-16 01:08
Okay, so digging into it, I have a function such as:

```
while RUNNING.load(Ordering::Relaxed) {
    async {
        check().await
    }
    .instrument(tracing::info_span!("monitor_upstream"))
    .await;
}
```

The panic is occurring with durations related to this instrumenting. This is seen by running with a different setup but we see:

```
  19:        0x1057edc94 - <core::time::Duration as core::ops::arith::Sub>::sub::hc7ad54c90819303e
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/time.rs:988:9
  20:        0x10501d9e8 - tracing_forest::tree::Span::base_duration::he5e8360005bda897
                               at /Users/william/development/tracing-forest/tracing-forest/src/tree/mod.rs:263:9
...
  33:        0x104f0f710 - core::ptr::drop_in_place<tracing::instrument::Instrumented<core::future::from_generator::GenFuture<opensuse_proxy_cache::monitor_upstream::{{closure}}::{{closure}}>>>::h74f0de7341eba579
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/ptr/mod.rs:188:1
  34:        0x104dc4f74 - opensuse_proxy_cache::monitor_upstream::{{closure}}::hecfc9fdae1d6d78c
                               at /Users/william/development/opensuse-proxy-cache/opensuse-proxy-cache/src/main.rs:288:61
```

I altered tree/mod to show the durations:

```
    pub fn base_duration(&self) -> Duration {
        eprintln!("{:?} - {:?}", self.total_duration, self.inner_duration);
        self.total_duration - self.inner_duration
    }
```

```
486.124µs - 830.703µs
```

So I suspect that there is some kind of counting-tracking shenanigans based on the fact that there is an inner await here, which causes the inner_duration to exceed the outer duration, potentially due to the outer await being parked or similar. 

Alternately it could just be a clock sync difference or similar. I'll defer to your knowledge on where these values come from :)

**Comment by Firstyear** [comment] 2022-03-16 01:27
Okay, I think I understand the problem. When you await inside a span, the spans are *exited* So adjusting my code such as:

```
while RUNNING.load(Ordering::Relaxed) {
    async {
         sleep(Duration::from_millis(2500)).await;
        check().await
    }
    .instrument(tracing::info_span!("monitor_upstream"))
    .await;
}
```

What occurs in a trace is that we immediately enter and then exit the monitor_upstream span. So the *await* time isn't being considered.

When you then have a child await, it gets a bit more hazy because I can see the upstream_monitor span being exited, but then only inner child spans being recording until their inner parts are complete. That's probably what creates the timing difference. 

So I *think* that your math here is a bit off as a result. I think you'll need to work out total_duration by calling elapsed inside of close() instead of exit(). That will give you the full time of this span from start to end.  

I don't think it's truly possible to work out "time spent in only this span" because you can't really account for await completely, but this would probably be a closer / better metric. Consider the above - exit() isn't callred until the await point in sleep, or even if it was an await 100 levels deep. So enter/exit() isn't truly working here because exit() needs to be called when you enter *any* child span, rather than when an await is hit. And that's not happening right now, we stay in this span until the await boundary. And then we don't return and enter again until that call stack full unwinds back into this span. 

So if you try to record time between enter()/exit() you'll end up timing this span *plus* the leading set of calls and executions UP TO an await, but then you won't time anything until that callstock full unwinds so your enter()/exit() timing is partial. 

Anyway, I suspect if you change total duration to be calculated by "close", and then you can use that instead, it'll avoid the crash here.

**Comment by Firstyear** [comment] 2022-03-16 01:34
To make it clearer perhaps:

```
async {
    async {
        async { 
            something().await
        }.instrument("inner")
    }.instrument("middle")
}.instrument("outer")
```

Here, the spans would record as:

```
enter outer
enter middle
enter inner
// await begins
exit middle
exit outer
// await is polled, not ready
enter inner
exit inner
// await is polled, is ready, starts to return
enter inner
exit inner
enter middle
exit middle
enter outer
exit outer
```

So you can see how once we hit the await boundary, the outer span is not re-entered until all the child spans close out and unwind. In a non-await context your code works, but await breaks this model. Thus, you need to use close() to determine the true timing from the start to the end, then you need to use the aggregate of the inner spans open/closes to work out their timings. 

I'm not sure there is a way to work otu the true timing for "how long I spent actually executing code" as a result. Unless you did a start/stop based on when you attach a child span and then re-enter perhaps?

**Comment by Firstyear** [comment] 2022-03-17 23:31
See https://github.com/QnnOkabayashi/tracing-forest/pull/13 

I think it may be related to the *type* of content in the await, with how it attaches and yields.

**Comment by QnnOkabayashi** [comment] 2022-03-22 04:35
By printing out the metadata of the span that was causing `Duration` overflow, I was able to find out that the `isahc`, a dependency of `surf`, is the culprit here . The problem is [here](https://github.com/sagebind/isahc/blob/master/src/handler.rs#L403-L404), where it manually assigns an existing span as the parent of a new span _without opening the parent_, and then _opens the child_. This allows child spans to accumulate open time without ever opening the parent, which is why the entered duration of the inner spans is greater than the entered duration of their parent span.

I'm not sure why Tracing allows for spans to have "parents" but not respect a stack structure, so I think a deeper understanding behind the design motivation of Tracing is required to proceed unless you have any better ideas.

**Comment by Firstyear** [comment] 2022-03-22 04:46
Well as much fun as it would be to debate the validity of this behaviour within the tracing framework, it is still a real issue that exists today with tracing forest. As a result, I think there needs to be defences from this (arguably broken) situation. 

So I still think this library needs to handle this in some manner to avoid weird state.

**Comment by Firstyear** [comment] 2022-03-22 04:51
perhaps the best option is a simple checked_sub, and make it returne an option<duration>, and to avoid the % calc in this borken situation (as well as flagging it)

**Comment by QnnOkabayashi** [comment] 2022-03-22 15:03
> perhaps the best option is a simple checked_sub, and make it returne an option, and to avoid the % calc in this borken situation (as well as flagging it)

I agree that this is a good bandaid fix. However, consider the case where a parent span, `P`, is manually assigned as the parent of a child span, `C`. Now, say `P` is entered, works for 5s, and then closes. Next, `C` enters _without entering `P`_, works for 4s, and then closes. The total time is roughly ~9s, and no red flags are raised since the child duration is less than the base duration.

With the current diagnostics, `tracing-forest` would say this program takes 5s, and it would be impossible to tell (with this fix) that anything bad ever happened. Worse, it would say that of those 5 seconds, `P` was only ever working for 1s outside of any child spans, which is a blatant lie. I'm not sure how we would check for this unless we checked that a span's parent is entered whenever it's entered, but this seems very expensive.

In terms of moving forward, here's what I think we should do:
1. Apply the bandaid fix like you said. Note that this won't fix the above case though.
2. Figure out the design motivation behind Tracing, and apply a long-term solution once we know what's going on to fix the above case. I've already opened an issue for that [here](https://github.com/tokio-rs/tracing/issues/2011).

**Comment by Firstyear** [comment] 2022-03-22 23:24
> > perhaps the best option is a simple checked_sub, and make it returne an option, and to avoid the % calc in this borken situation (as well as flagging it)
> 
> I agree that this is a good bandaid fix. However, consider the case where a parent span, `P`, is manually assigned as the parent of a child span, `C`. Now, say `P` is entered, works for 5s, and then closes. Next, `C` enters _without entering `P`_, works for 4s, and then closes. The total time is roughly ~9s, and no red flags are raised since the child duration is less than the base duration.
> 
> With the current diagnostics, `tracing-forest` would say this program takes 5s, and it would be impossible to tell (with this fix) that anything bad ever happened. Worse, it would say that of those 5 seconds, `P` was only ever working for 1s outside of any child spans, which is a blatant lie. I'm not sure how we would check for this unless we checked that a span's parent is entered whenever it's entered, but this seems very expensive.
> 
> In terms of moving forward, here's what I think we should do:
> 
> 1. Apply the bandaid fix like you said. Note that this won't fix the above case though.

Well, the issue is that even if you fix isahc/tracing, that it *may* be possible to create this situation again in another way, and you need to defend from that. Don't think of it as a bandaid, as much as a shield from unpredicted states. 

> 2. Figure out the design motivation behind Tracing, and apply a long-term solution once we know what's going on to fix the above case. I've already opened an issue for that [here](https://github.com/tokio-rs/tracing/issues/2011).

Awesome thanks!

**Comment by QnnOkabayashi** [comment] 2022-03-23 03:03
I think measuring time from creation to closing would be a bad idea, because then time across await boundaries would be considered. The Tracing people suggested just treating the parent span as opened anyways, which we could do as a span closes by just setting its total duration to the inner duration if it's greater, and maybe print a warning with it too.

I've also opened [another issue](https://github.com/sagebind/isahc/issues/386) in `isahc` to see if this is intentional.

**Comment by Firstyear** [comment] 2022-03-23 03:29
You actually want to know the await time too, because if you consider an operation you want to know for the real-user-time it took X seconds, while it's cpu time was only a part of that. So it would be good to also have that too but maybe that's a seperate issue, or it's own layer.

**Closed** 2022-03-24 03:54 UTC
